// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaToT5KNG4NrWgzDwDZg1Mag8vGTBdBLc',
    appId: '1:759893493253:web:79d1a0c513cf7409c4be6c',
    messagingSenderId: '759893493253',
    projectId: 'mindmap-b4058',
    authDomain: 'mindmap-b4058.firebaseapp.com',
    storageBucket: 'mindmap-b4058.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEGuz5te9oSEJQZ6G7WOZNevh9q4aAFIg',
    appId: '1:759893493253:android:80c2fc86bf54518ec4be6c',
    messagingSenderId: '759893493253',
    projectId: 'mindmap-b4058',
    storageBucket: 'mindmap-b4058.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqkN6D9NdykATQKjfRIVmnczu64JQGEWM',
    appId: '1:759893493253:ios:5532fc92b6835713c4be6c',
    messagingSenderId: '759893493253',
    projectId: 'mindmap-b4058',
    storageBucket: 'mindmap-b4058.appspot.com',
    iosBundleId: 'com.example.mindMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqkN6D9NdykATQKjfRIVmnczu64JQGEWM',
    appId: '1:759893493253:ios:53e818db8bacf7eec4be6c',
    messagingSenderId: '759893493253',
    projectId: 'mindmap-b4058',
    storageBucket: 'mindmap-b4058.appspot.com',
    iosBundleId: 'com.example.mindMap.RunnerTests',
  );
}
